# Generated by Django 6.0.5 on 2026-05-21 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Student',
        ),
    ]
